// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIpJZKZaijCV24X0HBovQFD76f9Fw79A',
    appId: '1:1053766253703:web:59687719668b669fb20c22',
    messagingSenderId: '1053766253703',
    projectId: 'training-b3250',
    authDomain: 'training-b3250.firebaseapp.com',
    storageBucket: 'training-b3250.firebasestorage.app',
    measurementId: 'G-L0HFSSEJJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWWlnsK05Jp1NYTC7aCLcdFCsE_WTnI0',
    appId: '1:1053766253703:android:4db173c09762a4a1b20c22',
    messagingSenderId: '1053766253703',
    projectId: 'training-b3250',
    storageBucket: 'training-b3250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGrgtW4UfMVeWpop3VqefmjOPFhiQxst8',
    appId: '1:1053766253703:ios:f58bdc600403183cb20c22',
    messagingSenderId: '1053766253703',
    projectId: 'training-b3250',
    storageBucket: 'training-b3250.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGrgtW4UfMVeWpop3VqefmjOPFhiQxst8',
    appId: '1:1053766253703:ios:f58bdc600403183cb20c22',
    messagingSenderId: '1053766253703',
    projectId: 'training-b3250',
    storageBucket: 'training-b3250.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIIpJZKZaijCV24X0HBovQFD76f9Fw79A',
    appId: '1:1053766253703:web:8a1a0520eb1165d7b20c22',
    messagingSenderId: '1053766253703',
    projectId: 'training-b3250',
    authDomain: 'training-b3250.firebaseapp.com',
    storageBucket: 'training-b3250.firebasestorage.app',
    measurementId: 'G-RCGF5NS9DG',
  );
}
